# Generated by Django 3.0.7 on 2020-06-20 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='الاسم',
            new_name='title',
        ),
    ]
