# Generated by Django 3.0.7 on 2020-06-22 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_order_notes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cart',
            unique_together=set(),
        ),
    ]
